= Endpoint

`Endpoint` stands for a part of URL, that can be used to make API calls (i.e. _https://jsonplaceholder.typicode.com,_ _https://jsonplaceholder.typicode.com/posts_ and underlying endpoints). This class allows you to define specific API calls with particular requests and their details.

If you want to define the "root" of an API, use the link:../../cheatsheets/annotations.adoc#_application[@Application] annotation, which will tell the framework what application configuration should it use.

.Sample of Api class use
[source,java]
```
@Application(name = "jsonplaceholder") // Define application endpoint root endpoint class
@ApiAuth(authType = ApiAuthMethod.NONE) // Define authentication method for any endpoint
public class JsonPlaceHolderApi extends RestEndpoint<JsonPlaceHolderApi> {
    public Posts posts; // Define child endpoints

    public JsonPlaceHolderApi(AOProps props) {
        super(props);
    }
}
```

== Supported API Implementations and Protocols

Primarily, *REST* APIs are supported using the _RestAssured_ framework. Other API implementations, like *SOAP*, are currently not supported, however the framework is ready for an easy additional implementation.

. link:./restendpoint-structure.adoc[Rest Endpoint]

== Default Endpoint Annotations

- link:../../cheatsheets/annotations.adoc#_endpointspecs[@EndpointSpecs]
- link:../../cheatsheets/annotations.adoc#_application[@Application]
- link:../../cheatsheets/annotations.adoc#_apiauth[@ApiAuth]