generalSettings:
  windowSize: maximized
  runMode: normal
  customTargetPath: "~/.m2/repository/webdriver"
  wait:
    waitsAutomatically: true
    timeouts:
      min: 8000
      mid: 20000
      max: 30000

chrome:
  arguments: []