
[#_endpoint_structure]
== Endpoint

`Endpoint` stands for a part of URL, that can be used to make API calls (i.e. _https://jsonplaceholder.typicode.com or _ _https://jsonplaceholder.typicode.com/posts_ and underlying endpoints). This class allows you to define specific API calls with particular requests and their details to that endpoint.

If you want to define the "root" of an API, use the xref:#_application_annotations[@Application] annotation, which will tell the framework what application configuration should it use.

.Sample of defining the REST API root endpoint
[source,java]
[source]
----
@Application(name = "jsonplaceholder") // Define application endpoint root endpoint class
@ApiAuth(authType = ApiAuthMethod.NONE) // Define authentication method for any endpoint
public class JsonPlaceHolderApi extends RestEndpoint<JsonPlaceHolderApi> {
    public Posts posts; // Define child endpoints

    public JsonPlaceHolderApi(AOProps props) {
        super(props);
    }
}
----

=== Supported API Implementations and Protocols

Primarily, *REST* APIs are supported using the _RestAssured_ framework. Other API implementations, like *SOAP*, are currently not supported, however the framework is ready for an easy additional implementation.

. xref:#_restendpoint_structure[Rest Endpoint]

include::restendpoint-structure.adoc[]

=== Default Endpoint Annotations

- xref:#_endpointspecs_annotations[@EndpointSpecs]
- xref:#_application_annotations[@Application]
- xref:#_apiauth_annotation[@ApiAuth]
