
[#_test_execution]
== Execution

=== Running Tests

Framework uses **TestNG** and **Maven** configuration to run tests. You can run tests as follows:

From an XML suite:

[source,bash]
----
mvn --projects <YOUR_PROJECT_MODULE_NAME> clean test -DsuiteXmlFile=<TESTNG-SUITE-FILE> -D<PARAMETER-NAME>=<PARAMETER-VALUE>
----

Mind that testing suites should be primarily located in _src/test/resources/testsets_ - you should enter path heading from this location to your test suite.

From a test class directly:

[source,bash]
----
mvn --projects <YOUR_PROJECT_MODULE_NAME> clean test -Dtest=<TEST-CLASS-NAME> -D<PARAMETER-NAME>=<PARAMETER-VALUE>
----

Launch maven test from core-automation-framework module:

[source,bash]
----
mvn --projects core-automation-framework clean test -Dtest=WebElementTests
----

Launch core-automation-framework unit tests suite:

[source,bash]
----
mvn --projects core-automation-framework clean test -DsuiteXmlFile=framework/unitTests.xml
----

=== Passing Parameters to the Test

You can pass parameters either by using the TestNG suite xml file, or directly with Maven command (see command sample above).

==== Parameters for Running Multiple Applications at Once

If your test uses more applications at once, it is recommended to write input parameters in format of `parameterName:applicationname`. In this way, you can supply parameter with same name for multiple projects with different values for each of the projects at once - supplying application name helps to assign parameter value to a specific application. Given parameter is used for all the applications in case of using multiple applications in one test without supplying application name to the parameter.

==== Passing Application Dependent Mandatory Parameters Through TestNG Suite

To pass application dependent mandatory parameter (i.e. like **environment**) using the TestNG suite, it is necessary to put this parameter directly under the `<suite>` or `<test>` tag. Other parameters can be passed through deeper levels of TestNG suite.

=== Framework Run Mode

You can set up framework run modes (**NORMAL**, **DEBUG**) adding `-DrunMode` Maven parameter to command with selected mode value. Run mode affects mainly log information that is being displayed in the console output. By default, **NORMAL** run mode is applied.

=== Test Results

Continue to the xref:#_reporting[reporting] section to learn how to generate test reports.
