= Inventi Automation Framework

Welcome to the official documentation for the *Inventi Automation Framework* - Java boilerplate for easier multi-platform test automation!

== Basic Information

*Inventi Automation Framework* is an ecosystem of libraries and design patterns that allows you to test various kinds and parts of applications with ease. The framework's main features are following:

* Testing of front-end of web applications
+
--
** Using *XPATH* locators to locate elements
** Easy to understand web page object structure following the *Page-Object pattern*
--
* Testing of back-end implementations (*REST*)
* Easy to understand API object structure
* *Multi-language* support
* Simultaneous testing of different applications
+
--
** Easily implement custom solution for your application type
--
* Better reporting and structure with *Allure reports*
* *Open-sourced*

=== Download

* link:https://git.inventi.cz/qa/development/java/automation-framework/-/releases[Latest release]
* link:https://git.inventi.cz/qa/development/java/automation-framework/[Inventi Automation Framework on GitLab]

=== Used Libraries

The framework's project is a Maven configuration using multiple third-party libraries for compiling, testing and in other phases. For more details about particular software used please visit appropriate POM files in the project. Below is provided basic information about software used along with developer's webpage and license type under which given software is supplied.

- link:https://docs.qameta.io/allure[Allure Framework] (Apache License 2.0)
- link:https://assertj.github.io/doc/[AssertJ] (Apache License 2.0)
- link:https://commons.apache.org[Apache Commons] (Apache License 2.0)
- link:https://logging.apache.org/log4j/2.x[Apache Log4J] (Apache License 2.0)
- link:https://www.eclipse.org/aspectj[AspectJ Weaver] (Eclipse Public License 1.0)
- link:https://github.com/google/guava[Google Guava] (Apache License 2.0) 
- link:https://hibernate.org/validator/[Hibernate Validator] (Apache License 2.0)
- link:https://github.com/FasterXML/jackson[Jackson] (Apache License 2.0)
- link:https://projectlombok.org[Lombok] (MIT License)
- link:http://maven.apache.org/surefire/maven-surefire-plugin[Maven SureFire Plugin] (Apache License 2.0)
- link:https://rest-assured.io[REST Assured] (Apache License 2.0)
- link:https://www.selenium.dev[Selenium WebDriver] (Apache License 2.0)
- link:https://testng.org/doc[TestNG] (Apache License 2.0)
- link:https://github.com/bonigarcia/webdrivermanager[WebDriverManager] (Apache License 2.0)

=== Licensing

The *Inventi Automation Framework* solution (`core-automation-framework` Maven module artifact) is distributed under *Apache License 2.0*. See attached link:https://git.inventi.cz/qa/development/java/automation-framework/-/blob/master/core-automation-framework/NOTICE[NOTICE] and link:https://git.inventi.cz/qa/development/java/automation-framework/-/blob/master/core-automation-framework/LICENSE[LICENSE] files located at the `core-automation-framework` folder for more information.

Other artifacts supplied along this project are meant for framework's usage demonstration purposes.

=== Support

In case of need for providing a closer look at the implementation, bug resolving or any other information, please contact link:https://git.inventi.cz/fenyktomas[@fenyktomas].